# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovidtav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='technology',
            field=models.IntegerField(blank=True, choices=[(0, 'Mind'), (1, 'R\xe9z'), (3, 'Optika'), (2, 'Koax'), (4, 'SAT')], db_column=b'technologia', null=True, verbose_name='Technol\xf3gia'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='technology',
            field=models.IntegerField(blank=True, choices=[(0, 'Mind'), (1, 'R\xe9z'), (3, 'Optika'), (2, 'Koax'), (4, 'SAT')], db_column=b'technologia', null=True, verbose_name='Technol\xf3gia'),
        ),
        migrations.AlterField(
            model_name='material',
            name='technology',
            field=models.IntegerField(blank=True, choices=[(0, 'Mind'), (1, 'R\xe9z'), (3, 'Optika'), (2, 'Koax'), (4, 'SAT')], db_column=b'technologia', null=True, verbose_name='Technol\xf3gia'),
        ),
    ]
