# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovidtav', '0002_auto_20161024_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketworkitem',
            name='amount',
            field=models.FloatField(db_column=b'mennyiseg', default=1, verbose_name='Mennyis\xe9g'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='technology',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (0, 'Mind'), (1, 'R\xe9z'), (3, 'Optika'), (2, 'Koax'), (4, 'SAT')], db_column=b'technologia', null=True, verbose_name='Technol\xf3gia'),
        ),
        migrations.AlterField(
            model_name='material',
            name='technology',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (0, 'Mind'), (1, 'R\xe9z'), (3, 'Optika'), (2, 'Koax'), (4, 'SAT')], db_column=b'technologia', null=True, verbose_name='Technol\xf3gia'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('\xdaj', '\xdaj'), ('Kiadva', 'Kiadva'), ('Folyamatban', 'Folyamatban'), ('Lez\xe1rva - K\xe9sz', 'Lez\xe1rva - K\xe9sz'), ('Lez\xe1rva - Eredm\xe9nytelen', 'Lez\xe1rva - Eredm\xe9nytelen'), ('Duplik\xe1lt', 'Duplik\xe1lt')], db_column=b'statusz', default='\xdaj', max_length=100, verbose_name='St\xe1tusz'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='technology',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (0, 'Mind'), (1, 'R\xe9z'), (3, 'Optika'), (2, 'Koax'), (4, 'SAT')], db_column=b'technologia', null=True, verbose_name='Technol\xf3gia'),
        ),
    ]
